### PR TITLE
Port to Webkit2 and changed the required import to Webkit2 API

### PR DESCRIPTION
**Pull request by cemeiq**
Port to Webkit2 and changed the required import to Webkit2 API

### CODE REVIEW

**Comment by chimosky** [comment]
Reviewed, thanks. 

`set_full_content_zoom` is deprecated and it's still being used in your code.

**Comment by cemeiq** [comment]
I will replace the deprecated method. Thanks

**Comment by chimosky** [comment]
Reviewed to 2b334a3, you only need to add `gi.require_version` in one file which you did in `activity.py`, you don't need the other ones.

**Comment by cemeiq** [comment]
I will remove the other gi.require_version from other files

**Comment by quozl** [comment]
Thanks.  Reviewed.  I've also fixed;
* a redundant `gi.require_version` call for Vte in activity.py,
* two redundant `gi.require_version` calls for Gdk and Gtk in graphics.py,
* `import gi` added to utils.py and reflectwindow.py,

**Pull request merged**
